baseURL = 'https://msay0sh1.github.io/'
languageCode = 'en-us'
title = 'Masayoshi Pages'
theme = 'ananke'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
	author = "Masayoshi_023"



[markup]
  defaultMarkdownHandler = 'goldmark'