baseURL = 'https://msay0sh1.github.io/'
languageCode = 'en-us'
title = 'Masayoshi Pages'
theme = 'ananke'

[menu]
	[[menu.main]]
		  identifier = "home"
		  name = "Home"
		  title = "home"
		  url = "/"

	[[menu.main]]
	  identifier = "posts"
	  name = "Post"
	  title = "Posts"
	  url = "/posts"

[caches]
  [caches.images]
    dir = ':cacheDir/images'