baseURL = 'https://msay0sh1.github.io/'
languageCode = 'en-us'
title = 'Masayoshi Pages'
theme = 'ananke'

[menu]
	[[menu.main]]
	  identifier = "about"
	  name = "About"
	  title = "About"
	  url = "/"

	[[menu.main]]
	  identifier = "posts"
	  name = "posts"
	  title = "Posts"
	  url = "/posts"

	[[menu.main]]
	  identifier = "github"
	  name = "github"
	  title = "GitHub"
	  url = "https://github.com/msay0sh1"