baseURL = 'https://msay0sh1.github.io/'
languageCode = 'en-us'
title = 'Masayoshi Pages'
theme = 'hello-friend-ng'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
	author = "Mikazuki"

	homeSubtitle = 'A Warrior, Athlete, Stoic, & Kind.'

	enableGlobalLanguageMenu = true


[markup]
  defaultMarkdownHandler = 'goldmark'